# Generated by Django 5.0.1 on 2025-05-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_payment_order_product_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
