# Generated by Django 5.0.1 on 2025-05-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_remove_product_product_delete_orderproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_total_other',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
